name: "owasp-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Change script permission
        run: |
          chmod +x scripts/zap-script.sh

      - name: ZAP scan
        run: scripts/zap-script.sh

      - name: Get ZAP Report
        id: get_report
        run: |
          # Assuming zap_baseline_report.html is in the root directory
          report_content=$(cat zap_baseline_report.html)
          echo "::set-output name=report_content::$report_content"

      - name: Post ZAP Report as Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.WORKSHOP6_GITHUB_TOKEN }}
          script: |
            const reportContent = github.context.payload.workflow_run.jobs.test.outputs.report_content;
            const issueComment = `
            **ZAP Scan Report:**
            \`\`\`
            ${reportContent}
            \`\`\`
            `;
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment,
            });


      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zap report
          path: |
            ./zap_baseline_report.html

